// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.16.0
// source: delay/delay.proto

package delay

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Delay_Register_FullMethodName = "/delay.Delay/Register"
)

// DelayClient is the client API for Delay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DelayClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
}

type delayClient struct {
	cc grpc.ClientConnInterface
}

func NewDelayClient(cc grpc.ClientConnInterface) DelayClient {
	return &delayClient{cc}
}

func (c *delayClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, Delay_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DelayServer is the server API for Delay service.
// All implementations must embed UnimplementedDelayServer
// for forward compatibility
type DelayServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	mustEmbedUnimplementedDelayServer()
}

// UnimplementedDelayServer must be embedded to have forward compatible implementations.
type UnimplementedDelayServer struct {
}

func (UnimplementedDelayServer) Register(context.Context, *RegisterRequest) (*RegisterReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDelayServer) mustEmbedUnimplementedDelayServer() {}

// UnsafeDelayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DelayServer will
// result in compilation errors.
type UnsafeDelayServer interface {
	mustEmbedUnimplementedDelayServer()
}

func RegisterDelayServer(s grpc.ServiceRegistrar, srv DelayServer) {
	s.RegisterService(&Delay_ServiceDesc, srv)
}

func _Delay_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DelayServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Delay_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DelayServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Delay_ServiceDesc is the grpc.ServiceDesc for Delay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Delay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "delay.Delay",
	HandlerType: (*DelayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Delay_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delay/delay.proto",
}
