// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.16.0
// source: delay/delay.proto

package delay

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/x-thooh/delay/api/proto/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	DelayTime     int64                  `protobuf:"varint,7,opt,name=delay_time,json=delayTime,proto3" json:"delay_time,omitempty"`
	Timeout       int64                  `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Backoff       []int64                `protobuf:"varint,9,rep,packed,name=backoff,proto3" json:"backoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_delay_delay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delay_delay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_delay_delay_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *RegisterRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegisterRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RegisterRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RegisterRequest) GetDelayTime() int64 {
	if x != nil {
		return x.DelayTime
	}
	return 0
}

func (x *RegisterRequest) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *RegisterRequest) GetBackoff() []int64 {
	if x != nil {
		return x.Backoff
	}
	return nil
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskNo        int64                  `protobuf:"varint,1,opt,name=task_no,json=taskNo,proto3" json:"task_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_delay_delay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_delay_delay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_delay_delay_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetTaskNo() int64 {
	if x != nil {
		return x.TaskNo
	}
	return 0
}

var File_delay_delay_proto protoreflect.FileDescriptor

const file_delay_delay_proto_rawDesc = "" +
	"\n" +
	"\x11delay/delay.proto\x12\x05delay\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\x1a\x1bvalidate/validate_ext.proto\"\xd8\x04\n" +
	"\x0fRegisterRequest\x12l\n" +
	"\x06schema\x18\x01 \x01(\tBT\xfaB\x1ar\x18R\x03FMTR\x04HTTPR\x05HTTPSR\x04GRPC\x8a\xb5\x183schema 必须是 FMT、HTTP、HTTPS 或 GRPC 之一R\x06schema\x12S\n" +
	"\x03url\x18\x02 \x01(\tBA\xfaB\ar\x05\x10\x01\x18\xff\x01\x8a\xb5\x183url 不能为空且长度不能超过 255 个字符R\x03url\x12V\n" +
	"\x04path\x18\x03 \x01(\tBB\xfaB\ar\x05\x10\x01\x18\xff\x01\x8a\xb5\x184path 不能为空且长度不能超过 255 个字符R\x04path\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x12X\n" +
	"\n" +
	"delay_time\x18\a \x01(\x03B9\xfaB\b\"\x06\x18\x80\xa3\x05(\x00\x8a\xb5\x18*delay_time 必须在 0 到 86400 秒之间R\tdelayTime\x12N\n" +
	"\atimeout\x18\b \x01(\x03B4\xfaB\a\"\x05\x18\x90\x1c(\x00\x8a\xb5\x18&timeout 必须在 0 到 3600 秒之间R\atimeout\x12S\n" +
	"\abackoff\x18\t \x03(\x03B9\xfaB\x05\x92\x01\x02\x10\x14\x8a\xb5\x18-backoff 数组长度不能超过 20 个元素R\abackoff\"(\n" +
	"\rRegisterReply\x12\x17\n" +
	"\atask_no\x18\x01 \x01(\x03R\x06taskNo2]\n" +
	"\x05Delay\x12T\n" +
	"\bRegister\x12\x16.delay.RegisterRequest\x1a\x14.delay.RegisterReply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/delay/registerB\x1aZ\x18github.com/x-thooh/delayb\x06proto3"

var (
	file_delay_delay_proto_rawDescOnce sync.Once
	file_delay_delay_proto_rawDescData []byte
)

func file_delay_delay_proto_rawDescGZIP() []byte {
	file_delay_delay_proto_rawDescOnce.Do(func() {
		file_delay_delay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delay_delay_proto_rawDesc), len(file_delay_delay_proto_rawDesc)))
	})
	return file_delay_delay_proto_rawDescData
}

var file_delay_delay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_delay_delay_proto_goTypes = []any{
	(*RegisterRequest)(nil), // 0: delay.RegisterRequest
	(*RegisterReply)(nil),   // 1: delay.RegisterReply
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_delay_delay_proto_depIdxs = []int32{
	2, // 0: delay.RegisterRequest.data:type_name -> google.protobuf.Struct
	0, // 1: delay.Delay.Register:input_type -> delay.RegisterRequest
	1, // 2: delay.Delay.Register:output_type -> delay.RegisterReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_delay_delay_proto_init() }
func file_delay_delay_proto_init() {
	if File_delay_delay_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delay_delay_proto_rawDesc), len(file_delay_delay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delay_delay_proto_goTypes,
		DependencyIndexes: file_delay_delay_proto_depIdxs,
		MessageInfos:      file_delay_delay_proto_msgTypes,
	}.Build()
	File_delay_delay_proto = out.File
	file_delay_delay_proto_goTypes = nil
	file_delay_delay_proto_depIdxs = nil
}
