// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.16.0
// source: validate_ext.proto

package validate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_validate_ext_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "validate_ext.custom_error",
		Tag:           "bytes,50001,opt,name=custom_error",
		Filename:      "validate_ext.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string custom_error = 50001;
	E_CustomError = &file_validate_ext_proto_extTypes[0]
)

var File_validate_ext_proto protoreflect.FileDescriptor

const file_validate_ext_proto_rawDesc = "" +
	"\n" +
	"\x12validate_ext.proto\x12\fvalidate_ext\x1a google/protobuf/descriptor.proto:B\n" +
	"\fcustom_error\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\vcustomErrorB6Z4github.com/x-thooh/delay/api/proto/validate;validateb\x06proto3"

var file_validate_ext_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_validate_ext_proto_depIdxs = []int32{
	0, // 0: validate_ext.custom_error:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_validate_ext_proto_init() }
func file_validate_ext_proto_init() {
	if File_validate_ext_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validate_ext_proto_rawDesc), len(file_validate_ext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_validate_ext_proto_goTypes,
		DependencyIndexes: file_validate_ext_proto_depIdxs,
		ExtensionInfos:    file_validate_ext_proto_extTypes,
	}.Build()
	File_validate_ext_proto = out.File
	file_validate_ext_proto_goTypes = nil
	file_validate_ext_proto_depIdxs = nil
}
