// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.16.0
// source: example/example.proto

package delay

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_example_example_proto protoreflect.FileDescriptor

const file_example_example_proto_rawDesc = "" +
	"\n" +
	"\x15example/example.proto\x12\aexample\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto2^\n" +
	"\aExample\x12S\n" +
	"\x05Valid\x12\x17.google.protobuf.Struct\x1a\x16.google.protobuf.Value\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/example/validB\x1aZ\x18github.com/x-thooh/delayb\x06proto3"

var file_example_example_proto_goTypes = []any{
	(*structpb.Struct)(nil), // 0: google.protobuf.Struct
	(*structpb.Value)(nil),  // 1: google.protobuf.Value
}
var file_example_example_proto_depIdxs = []int32{
	0, // 0: example.Example.Valid:input_type -> google.protobuf.Struct
	1, // 1: example.Example.Valid:output_type -> google.protobuf.Value
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_example_proto_init() }
func file_example_example_proto_init() {
	if File_example_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_example_proto_rawDesc), len(file_example_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_example_proto_goTypes,
		DependencyIndexes: file_example_example_proto_depIdxs,
	}.Build()
	File_example_example_proto = out.File
	file_example_example_proto_goTypes = nil
	file_example_example_proto_depIdxs = nil
}
