// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/x-thooh/delay/internal/boot/database"
	"github.com/x-thooh/delay/internal/boot/logger"
	"github.com/x-thooh/delay/internal/config"
	"github.com/x-thooh/delay/internal/server/grpc"
	"github.com/x-thooh/delay/internal/server/http"
	"github.com/x-thooh/delay/internal/service"
	"github.com/x-thooh/delay/internal/service/delay"
	"github.com/x-thooh/delay/internal/service/example"
	"github.com/x-thooh/delay/pkg/app"
)

// Injectors from wire.go:

// wireApp init app application.
func wireApp(entity *config.Entity) (*app.App, func(), error) {
	logConfig := config.RegisterLogger(entity)
	logLogger, cleanup, err := logger.InitLogger(logConfig)
	if err != nil {
		return nil, nil, err
	}
	httpConfig := config.RegisterHTTP(entity)
	server := http.New(httpConfig)
	grpcConfig := config.RegisterGRPC(entity)
	storageConfig := config.RegisterTimingWheel(entity)
	databaseConfig := config.RegisterDatabase(entity)
	db, err := database.InitSQLX(logLogger, databaseConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	storage, err := service.RegisterStorage(storageConfig, logLogger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	delayServer := delay.New(storage)
	exampleServer := example.New(logLogger)
	grpcServer := grpc.New(grpcConfig, logLogger, delayServer, exampleServer)
	appApp := newApp(logLogger, server, grpcServer, storage)
	return appApp, func() {
		cleanup()
	}, nil
}
